### ISSUE TITLE
关于封装后的每个item文字显示问题？

### ISSUE THREAD

**Issue by baoyachi** [hongyangAndroid/FlexboxLayout-Tag#1]
运行项目，将“Button”添加了几个字符为"Button1231ds"，为了测试显示的布局，发现下图的"Hello"文字显示不全，只显示“hell”，求解答？

![f8fcb077-d88e-4568-ba01-eca134981d17](https://cloud.githubusercontent.com/assets/10433001/15416285/27a8b2fa-1e7c-11e6-87c8-5ec4b68dea50.png)

**Comment by lewiswon** [comment]
我也碰到了这个问题，请问有好的解决方法吗？

**Comment by lewiswon** [comment]
https://github.com/google/flexbox-layout/issues/36  可能是这个原因，你可以去看看

**Comment by tcqq** [comment]
版本修改为最新版本：
compile 'com.google.android:flexbox:0.3.0'

TagFlowLayout.java中53和54行代码替换成以下代码：

setFlexDirection(FlexDirection.ROW);
setFlexWrap(FlexWrap.WRAP);

即可解决
